package com.rvtechnologies.grigorahq.utils

object PrefConstants {
    val PREF_NAME = "grigora"
    val TOKEN = "access_token"
    val NAME = "name"
    val FRENCH_NAME = "french_name"
    val TOKEN_TYPE = "token_type"
    val EMAIL = "email"
    val PHONE = "phone"
    val IMAGE = "image"
    val PROOF = "id_proof"
    val ROLE = "role"
    val ADDRESS = "address"
    val FRENCH_ADDRESS = "french_address"
    val ID = "id"
    val LAT = "lat"
    val LONG = "long"
    val LANGUAGE = "language"
    val PURE_VEG = "pure_veg"
    val OFFER = "offer"
    val CREATED_AT = "created_at"
    val WALLET = "wallet"
    val RATING = "rating"
    val RECIEPT_NUMBER = "receipt_number"
    val ACCOUNT_NUMBER = "account_number"
    val OPENING_TIME = "open_time"
    val FULL_TIME = "full_time"
    val PICKUP = "pickup"
    val BUSY_STATUS = "busy_status"

    val CLOSING_TIME = "close_time"
    val QUIZ_JOIN = "quiz_join"
    val MAP_KEY="AIzaSyDo51Rxb7QMQ_bKj3hBmZ6Ty8p7BYp7oWU"
}