package com.rvtechnologies.grigorahq.network

class NetworkConstants {
    companion object {
//        const val BASE_URL = "http://3.13.78.53/GriGora/public/api/"
        const val BASE_URL = "http://3.13.78.53/api/"
        const val signup = "signup"
        const val login = "login"
        const val add_category = "add-category"
        const val get_categories = "get-parent-categories"
        const val add_item = "add-item"
        const val edit_item = "edit-item"
        const val delete_item = "delete-item/"
        const val category_item_list = "category-item-list/"
        const val delete_category = "delete-category/"
        const val edit_category = "edit-category"
        const val logout = "logout"
        const val forgot_password = "forgot-password"
        const val get_cuisine = "get-cuisine"
        const val complete_profile = "complete-profile"
        const val update_user_token = "update-user-token"
        const val restaurant_orders = "restaurant-orders"
        const val restaurant_accept_order = "restaurant-accept-order"
        const val restaurant_items_list = "restaurant-items-list"
        const val notofication_driver = "notofication_driver"
        const val update_item = "edit-item"
        const val available_status = "available-status"
        const val restaurant_offer = "restaurant-offer"
        const val promocode_list = "promocode-list/"
        const val assign_promo_to_restaurant = "assign-promo-to-restaurant"
        const val restaurant_new_orders = "restaurant-new-orders"
        const val restaurant_past_orders = "restaurant-past-orders"
        const val restaurant_ongoing_orders = "restaurant-ongoing-orders"
        const val change_password = "change-password"
        const val edit_profile = "edit-profile"
        const val order_almost_prepared = "order-almost-prepared"
        const val get_wallet = "get-wallet"
        const val wallet_history = "wallet-history"
        const val contact_us = "contact-us"
        const val get_account_details = "get-account-details"
        const val save_account_details = "save-account-details"
        const val payout = "payout"
        const val add_cuisine = "add-cuisine"
        const val current_orders_location = "current-orders-location"
        const val get_brands = "get-brands"
        const val cancel_reasons = "cancel-reasons"
        const val near_by_drivers = "near-by-drivers"
        const val booking_available = "booking-available"
        const val new_bookings = "new-bookings"
        const val accept_booking = "accept-booking"
        const val quiz_question = "quiz-question"
        const val complete_pickup_order = "complete-pickup-order/"
        const val join_quiz = "join-quiz"
        const val change_item_availabilty_status = "change-item-availabilty-status"
        const val update_time = "update/time"
        const val get_userinfo = "get-userinfo"
        const val start_preparing = "start-preparing"
        const val change_language = "change-language/"
        const val remove_promo_to_restaurant = "assign-promo-to-restaurant"
        const val change_restaurant_booking_status = "change-restaurant-booking-status"
        const val add_parent_cuisine = "add-parent-cuisine"
        const val get_parent_cuisine = "get-parent-cuisine"
        const val mark_unmark_featured = "mark-unmark-featured"
    }
}