package com.rvtechnologies.grigorahq.services.models

data class ResetPromoModel(
    val `data`: Data,
    val message: String,
    val status: Boolean
) {
    data class Data(
        val address: String,
        val address_proof: Any,
        val approved: String,
        val busy_status: String,
        val closing_time: String,
        val created_at: String,
        val device_token: String,
        val device_type: String,
        val email: String,
        val email_verified_at: Any,
        val facebook_id: Any,
        val franchisee_proof: String,
        val french_address: String,
        val french_name: String,
        val from_referal: Any,
        val full_time: String,
        val google_id: Any,
        val id: Int,
        val id_proof: String,
        val image: String,
        val instagram_id: Any,
        val language: String,
        val latitude: String,
        val license_image: String,
        val longitude: String,
        val my_referal: Any,
        val name: String,
        val no_of_seats: Int,
        val notification: String,
        val offer: Int,
        val opening_time: String,
        val otp: Any,
        val otp_expire_time: Any,
        val phone: String,
        val pickup: String,
        val preparing_time: Int,
        val promo_id: Int,
        val pure_veg: String,
        val receipt_id: String,
        val role: String,
        val status: String,
        val table_booking: String,
        val twiter_id: Any,
        val updated_at: String,
        val username: String,
        val wallet: String
    )
}